import type { FeatureDefinition } from '../core/types.js';

function feature(
  partial: Omit<FeatureDefinition, 'packages' | 'env' | 'dockerServices' | 'conflicts' | 'dependencies' | 'installer'> &
    Partial<Pick<FeatureDefinition, 'packages' | 'env' | 'dockerServices' | 'conflicts' | 'dependencies' | 'installer'>>,
): FeatureDefinition {
  return {
    packages: [],
    env: [],
    dockerServices: [],
    conflicts: [],
    dependencies: [],
    installer: partial.id,
    ...partial,
  };
}

export const FEATURE_CATALOG: FeatureDefinition[] = [
  feature({ id: 'language-typescript', name: 'TypeScript', category: 'language', description: 'Strict TypeScript project.' }),
  feature({ id: 'language-javascript', name: 'JavaScript', category: 'language', description: 'JavaScript project.', conflicts: ['language-typescript'] }),
  feature({ id: 'pm-pnpm', name: 'pnpm', category: 'tooling', description: 'pnpm package manager.' }),
  feature({ id: 'pm-npm', name: 'npm', category: 'tooling', description: 'npm package manager.', conflicts: ['pm-pnpm', 'pm-yarn', 'pm-bun'] }),
  feature({ id: 'pm-yarn', name: 'Yarn', category: 'tooling', description: 'Yarn package manager.', conflicts: ['pm-pnpm', 'pm-npm', 'pm-bun'] }),
  feature({ id: 'pm-bun', name: 'Bun', category: 'tooling', description: 'Bun package manager.', conflicts: ['pm-pnpm', 'pm-npm', 'pm-yarn'] }),
  feature({
    id: 'backend-express',
    name: 'Express',
    category: 'backend',
    description: 'Express.js HTTP server.',
    packages: [{ name: 'express', version: '^4.21.2', workspace: 'api' }],
  }),
  feature({
    id: 'backend-fastify',
    name: 'Fastify',
    category: 'backend',
    description: 'Fastify HTTP server.',
    conflicts: ['backend-express'],
    packages: [{ name: 'fastify', version: '^5.2.1', workspace: 'api' }],
  }),
  feature({ id: 'api-rest', name: 'REST', category: 'api', description: 'Versioned REST API.' }),
  feature({
    id: 'api-graphql',
    name: 'GraphQL',
    category: 'api',
    description: 'GraphQL API.',
  }),
  feature({
    id: 'graphql-apollo',
    name: 'Apollo Server',
    category: 'api',
    description: 'Apollo GraphQL server.',
    dependencies: ['api-graphql'],
    packages: [{ name: '@apollo/server', version: '^4.11.3', workspace: 'api' }],
  }),
  feature({
    id: 'graphql-yoga',
    name: 'GraphQL Yoga',
    category: 'api',
    description: 'GraphQL Yoga server.',
    dependencies: ['api-graphql'],
    conflicts: ['graphql-apollo'],
    packages: [{ name: 'graphql-yoga', version: '^5.13.1', workspace: 'api' }],
  }),
  feature({
    id: 'orm-prisma',
    name: 'Prisma',
    category: 'database',
    description: 'Prisma ORM.',
    packages: [
      { name: '@prisma/client', version: '^6.5.0', workspace: 'api' },
      { name: 'prisma', version: '^6.5.0', workspace: 'api', dev: true },
    ],
  }),
  feature({
    id: 'orm-drizzle',
    name: 'Drizzle',
    category: 'database',
    description: 'Drizzle ORM.',
    conflicts: ['orm-prisma', 'orm-typeorm', 'orm-sequelize', 'orm-knex', 'orm-pg'],
    packages: [
      { name: 'drizzle-orm', version: '^0.44.4', workspace: 'api' },
      { name: 'drizzle-kit', version: '^0.31.4', workspace: 'api', dev: true },
    ],
  }),
  feature({
    id: 'orm-typeorm',
    name: 'TypeORM',
    category: 'database',
    description: 'TypeORM.',
    conflicts: ['orm-prisma', 'orm-drizzle', 'orm-sequelize', 'orm-knex', 'orm-pg'],
    packages: [{ name: 'typeorm', version: '^0.3.22', workspace: 'api' }],
  }),
  feature({
    id: 'orm-sequelize',
    name: 'Sequelize',
    category: 'database',
    description: 'Sequelize ORM.',
    conflicts: ['orm-prisma', 'orm-drizzle', 'orm-typeorm', 'orm-knex', 'orm-pg'],
    packages: [{ name: 'sequelize', version: '^6.37.6', workspace: 'api' }],
  }),
  feature({
    id: 'orm-knex',
    name: 'Knex',
    category: 'database',
    description: 'Knex query builder.',
    conflicts: ['orm-prisma', 'orm-drizzle', 'orm-typeorm', 'orm-sequelize', 'orm-pg'],
    packages: [{ name: 'knex', version: '^3.1.0', workspace: 'api' }],
  }),
  feature({
    id: 'orm-pg',
    name: 'Raw pg',
    category: 'database',
    description: 'node-postgres without an ORM.',
    conflicts: ['orm-prisma', 'orm-drizzle', 'orm-typeorm', 'orm-sequelize', 'orm-knex'],
    packages: [{ name: 'pg', version: '^8.14.1', workspace: 'api' }],
  }),
  feature({
    id: 'db-postgresql',
    name: 'PostgreSQL',
    category: 'database',
    description: 'PostgreSQL database.',
    env: [{ key: 'DATABASE_URL', example: 'postgresql://postgres:postgres@localhost:5432/app?schema=public', required: true, description: 'PostgreSQL connection string', workspace: 'api' }],
    dockerServices: ['postgres'],
  }),
  feature({ id: 'auth-jwt', name: 'JWT', category: 'auth', description: 'JWT access tokens.' }),
  feature({
    id: 'auth-jwt-refresh-token',
    name: 'JWT + Refresh Token',
    category: 'auth',
    description: 'Short-lived access tokens with rotating refresh tokens.',
    env: [
      { key: 'JWT_SECRET', example: 'change-me-access-secret-min-32-chars-long', required: true, description: 'Access token secret', workspace: 'api', secret: true },
      { key: 'JWT_REFRESH_SECRET', example: 'change-me-refresh-secret-min-32-chars', required: true, description: 'Refresh token secret', workspace: 'api', secret: true },
    ],
    packages: [{ name: 'jsonwebtoken', version: '^9.0.2', workspace: 'api' }],
  }),
  feature({
    id: 'auth-session',
    name: 'Session',
    category: 'auth',
    description: 'Cookie session authentication.',
    packages: [{ name: 'express-session', version: '^1.18.1', workspace: 'api' }],
  }),
  feature({ id: 'auth-oauth2', name: 'OAuth2', category: 'auth', description: 'OAuth2 authorization-code flow.' }),
  feature({
    id: 'hash-argon2id',
    name: 'Argon2id',
    category: 'auth',
    description: 'Argon2id password hashing.',
    packages: [{ name: 'argon2', version: '^0.41.1', workspace: 'api' }],
  }),
  feature({
    id: 'hash-bcrypt',
    name: 'bcrypt',
    category: 'auth',
    description: 'bcrypt password hashing.',
    conflicts: ['hash-argon2id'],
    packages: [{ name: 'bcryptjs', version: '^3.0.2', workspace: 'api' }],
  }),
  feature({ id: 'oauth-google', name: 'Google OAuth', category: 'auth', description: 'Google social login.', dependencies: ['auth-oauth2'] }),
  feature({ id: 'oauth-github', name: 'GitHub OAuth', category: 'auth', description: 'GitHub social login.', dependencies: ['auth-oauth2'] }),
  feature({ id: 'oauth-facebook', name: 'Facebook OAuth', category: 'auth', description: 'Facebook social login.', dependencies: ['auth-oauth2'] }),
  feature({ id: 'oauth-microsoft', name: 'Microsoft OAuth', category: 'auth', description: 'Microsoft social login.', dependencies: ['auth-oauth2'] }),
  feature({ id: 'oauth-apple', name: 'Apple OAuth', category: 'auth', description: 'Apple social login.', dependencies: ['auth-oauth2'] }),
  feature({ id: 'oauth-linkedin', name: 'LinkedIn OAuth', category: 'auth', description: 'LinkedIn social login.', dependencies: ['auth-oauth2'] }),
  feature({ id: 'rbac-custom', name: 'Custom RBAC', category: 'auth', description: 'Roles and permissions tables.' }),
  feature({
    id: 'rbac-casl',
    name: 'CASL',
    category: 'auth',
    description: 'CASL authorization.',
    packages: [{ name: '@casl/ability', version: '^6.7.3', workspace: 'api' }],
  }),
  feature({
    id: 'rbac-accesscontrol',
    name: 'AccessControl',
    category: 'auth',
    description: 'accesscontrol RBAC.',
    packages: [{ name: 'accesscontrol', version: '^2.2.1', workspace: 'api' }],
  }),
  feature({ id: 'frontend-vite-react', name: 'React + Vite', category: 'frontend', description: 'Vite React SPA.' }),
  feature({ id: 'frontend-nextjs', name: 'Next.js', category: 'frontend', description: 'Next.js frontend.', conflicts: ['frontend-vite-react'] }),
  feature({ id: 'ui-tailwind', name: 'Tailwind CSS', category: 'frontend', description: 'Tailwind CSS.' }),
  feature({ id: 'ui-shadcn', name: 'shadcn/ui', category: 'frontend', description: 'shadcn/ui on Tailwind.', dependencies: ['ui-tailwind'] }),
  feature({ id: 'ui-mui', name: 'Material UI', category: 'frontend', description: 'MUI components.' }),
  feature({ id: 'ui-antd', name: 'Ant Design', category: 'frontend', description: 'Ant Design components.' }),
  feature({ id: 'ui-chakra', name: 'Chakra UI', category: 'frontend', description: 'Chakra UI components.' }),
  feature({ id: 'ui-headless', name: 'Headless UI', category: 'frontend', description: 'Headless UI primitives.' }),
  feature({
    id: 'state-zustand',
    name: 'Zustand',
    category: 'frontend',
    description: 'Zustand client state.',
    packages: [{ name: 'zustand', version: '^5.0.3', workspace: 'web' }],
  }),
  feature({
    id: 'state-redux',
    name: 'Redux Toolkit',
    category: 'frontend',
    description: 'Redux Toolkit.',
    conflicts: ['state-zustand', 'state-jotai'],
    packages: [{ name: '@reduxjs/toolkit', version: '^2.6.1', workspace: 'web' }],
  }),
  feature({
    id: 'state-jotai',
    name: 'Jotai',
    category: 'frontend',
    description: 'Jotai atomic state.',
    conflicts: ['state-zustand', 'state-redux'],
    packages: [{ name: 'jotai', version: '^2.12.2', workspace: 'web' }],
  }),
  feature({
    id: 'query-tanstack-query',
    name: 'TanStack Query',
    category: 'frontend',
    description: 'Server state with TanStack Query.',
    packages: [{ name: '@tanstack/react-query', version: '^5.69.0', workspace: 'web' }],
  }),
  feature({
    id: 'query-swr',
    name: 'SWR',
    category: 'frontend',
    description: 'SWR data fetching.',
    conflicts: ['query-tanstack-query'],
    packages: [{ name: 'swr', version: '^2.3.3', workspace: 'web' }],
  }),
  feature({
    id: 'forms-react-hook-form',
    name: 'React Hook Form',
    category: 'frontend',
    description: 'React Hook Form.',
    packages: [{ name: 'react-hook-form', version: '^7.54.2', workspace: 'web' }],
  }),
  feature({
    id: 'forms-formik',
    name: 'Formik',
    category: 'frontend',
    description: 'Formik forms.',
    conflicts: ['forms-react-hook-form'],
    packages: [{ name: 'formik', version: '^2.4.6', workspace: 'web' }],
  }),
  feature({
    id: 'validation-zod',
    name: 'Zod',
    category: 'validation',
    description: 'Zod schema validation.',
    packages: [{ name: 'zod', version: '^3.24.2', workspace: 'api' }],
  }),
  feature({ id: 'validation-yup', name: 'Yup', category: 'validation', description: 'Yup validation.', conflicts: ['validation-zod', 'validation-valibot', 'validation-joi'] }),
  feature({ id: 'validation-valibot', name: 'Valibot', category: 'validation', description: 'Valibot validation.', conflicts: ['validation-zod', 'validation-yup', 'validation-joi'] }),
  feature({ id: 'validation-joi', name: 'Joi', category: 'validation', description: 'Joi validation.', conflicts: ['validation-zod', 'validation-yup', 'validation-valibot'] }),
  feature({
    id: 'client-axios',
    name: 'Axios',
    category: 'frontend',
    description: 'Axios HTTP client.',
    packages: [{ name: 'axios', version: '^1.8.4', workspace: 'web' }],
  }),
  feature({ id: 'client-fetch', name: 'Fetch', category: 'frontend', description: 'Native fetch client.', conflicts: ['client-axios'] }),
  feature({
    id: 'cache-redis',
    name: 'Redis',
    category: 'infra',
    description: 'Redis cache, sessions, rate limits, and pub/sub.',
    packages: [{ name: 'ioredis', version: '^5.6.0', workspace: 'api' }],
    env: [{ key: 'REDIS_URL', example: 'redis://localhost:6379', required: true, description: 'Redis connection URL', workspace: 'api' }],
    dockerServices: ['redis'],
  }),
  feature({
    id: 'queue-bullmq',
    name: 'BullMQ',
    category: 'infra',
    description: 'Redis-backed job queue.',
    dependencies: ['cache-redis'],
    packages: [{ name: 'bullmq', version: '^5.44.4', workspace: 'api' }],
  }),
  feature({ id: 'storage-local', name: 'Local storage', category: 'storage', description: 'Local disk uploads.' }),
  feature({
    id: 'storage-s3',
    name: 'AWS S3',
    category: 'storage',
    description: 'S3 object storage.',
    packages: [{ name: '@aws-sdk/client-s3', version: '^3.782.0', workspace: 'api' }],
  }),
  feature({ id: 'storage-r2', name: 'Cloudflare R2', category: 'storage', description: 'R2 S3-compatible storage.' }),
  feature({
    id: 'storage-minio',
    name: 'MinIO',
    category: 'storage',
    description: 'MinIO object storage.',
    dockerServices: ['minio'],
  }),
  feature({ id: 'email-smtp', name: 'SMTP', category: 'email', description: 'Generic SMTP transport.' }),
  feature({
    id: 'email-resend',
    name: 'Resend',
    category: 'email',
    description: 'Resend email API.',
    packages: [{ name: 'resend', version: '^4.2.0', workspace: 'api' }],
    env: [{ key: 'RESEND_API_KEY', example: 're_xxxxxxxxx', required: true, description: 'Resend API key', workspace: 'api', secret: true }],
  }),
  feature({ id: 'email-sendgrid', name: 'SendGrid', category: 'email', description: 'SendGrid email.' }),
  feature({ id: 'email-ses', name: 'Amazon SES', category: 'email', description: 'Amazon SES.' }),
  feature({ id: 'email-mailgun', name: 'Mailgun', category: 'email', description: 'Mailgun email.' }),
  feature({ id: 'email-postmark', name: 'Postmark', category: 'email', description: 'Postmark email.' }),
  feature({ id: 'mailpit', name: 'Mailpit', category: 'email', description: 'Local email catcher.', dockerServices: ['mailpit'] }),
  feature({ id: 'notify-email', name: 'Email notifications', category: 'notifications', description: 'Email notification channel.' }),
  feature({ id: 'notify-database', name: 'Database notifications', category: 'notifications', description: 'Persisted in-app notifications.' }),
  feature({ id: 'notify-push', name: 'Push notifications', category: 'notifications', description: 'Web push notifications.' }),
  feature({ id: 'notify-sms', name: 'SMS notifications', category: 'notifications', description: 'SMS notification channel.' }),
  feature({ id: 'notify-slack', name: 'Slack notifications', category: 'notifications', description: 'Slack notification channel.' }),
  feature({
    id: 'pay-stripe',
    name: 'Stripe',
    category: 'payments',
    description: 'Stripe payments.',
    packages: [{ name: 'stripe', version: '^17.7.0', workspace: 'api' }],
    env: [
      { key: 'STRIPE_SECRET_KEY', example: 'sk_test_xxx', required: true, description: 'Stripe secret key', workspace: 'api', secret: true },
      { key: 'STRIPE_WEBHOOK_SECRET', example: 'whsec_xxx', required: true, description: 'Stripe webhook secret', workspace: 'api', secret: true },
    ],
  }),
  feature({ id: 'pay-paypal', name: 'PayPal', category: 'payments', description: 'PayPal payments.' }),
  feature({ id: 'pay-bkash', name: 'bKash', category: 'payments', description: 'bKash payments.' }),
  feature({ id: 'pay-nagad', name: 'Nagad', category: 'payments', description: 'Nagad payments.' }),
  feature({ id: 'pay-sslcommerz', name: 'SSLCommerz', category: 'payments', description: 'SSLCommerz payments.' }),
  feature({ id: 'pay-razorpay', name: 'Razorpay', category: 'payments', description: 'Razorpay payments.' }),
  feature({
    id: 'ws-socket.io',
    name: 'Socket.IO',
    category: 'realtime',
    description: 'Socket.IO websockets.',
    packages: [{ name: 'socket.io', version: '^4.8.1', workspace: 'api' }],
  }),
  feature({ id: 'ws-ws', name: 'ws', category: 'realtime', description: 'Native WebSocket server.', packages: [{ name: 'ws', version: '^8.18.1', workspace: 'api' }] }),
  feature({ id: 'search-postgres-fts', name: 'PostgreSQL Full Text', category: 'search', description: 'Postgres full-text search.' }),
  feature({ id: 'search-meilisearch', name: 'Meilisearch', category: 'search', description: 'Meilisearch engine.' }),
  feature({ id: 'search-elasticsearch', name: 'Elasticsearch', category: 'search', description: 'Elasticsearch engine.' }),
  feature({ id: 'search-opensearch', name: 'OpenSearch', category: 'search', description: 'OpenSearch engine.' }),
  feature({
    id: 'log-pino',
    name: 'Pino',
    category: 'observability',
    description: 'Structured Pino logging.',
    packages: [{ name: 'pino', version: '^9.6.0', workspace: 'api' }],
  }),
  feature({
    id: 'log-winston',
    name: 'Winston',
    category: 'observability',
    description: 'Winston logging.',
    conflicts: ['log-pino'],
    packages: [{ name: 'winston', version: '^3.17.0', workspace: 'api' }],
  }),
  feature({
    id: 'mon-sentry',
    name: 'Sentry',
    category: 'observability',
    description: 'Sentry error monitoring.',
    env: [{ key: 'SENTRY_DSN', example: '', required: false, description: 'Sentry DSN', workspace: 'api', secret: true }],
  }),
  feature({ id: 'mon-opentelemetry', name: 'OpenTelemetry', category: 'observability', description: 'OpenTelemetry tracing.' }),
  feature({ id: 'mon-prometheus', name: 'Prometheus', category: 'observability', description: 'Prometheus metrics.' }),
  feature({ id: 'mon-health', name: 'Health checks', category: 'observability', description: '/health and /ready endpoints.' }),
  feature({ id: 'test-vitest', name: 'Vitest', category: 'testing', description: 'Vitest unit and integration tests.' }),
  feature({ id: 'test-jest', name: 'Jest', category: 'testing', description: 'Jest tests.', conflicts: ['test-vitest'] }),
  feature({ id: 'e2e-playwright', name: 'Playwright', category: 'testing', description: 'Playwright E2E tests.' }),
  feature({ id: 'e2e-cypress', name: 'Cypress', category: 'testing', description: 'Cypress E2E tests.', conflicts: ['e2e-playwright'] }),
  feature({ id: 'docker-dev', name: 'Docker (dev)', category: 'infra', description: 'Development Compose stack.' }),
  feature({ id: 'docker-prod', name: 'Docker (prod)', category: 'infra', description: 'Production images and Compose.', dependencies: ['docker-dev'] }),
  feature({ id: 'cicd-github-actions', name: 'GitHub Actions', category: 'cicd', description: 'GitHub Actions pipeline.' }),
  feature({ id: 'cicd-gitlab-ci', name: 'GitLab CI', category: 'cicd', description: 'GitLab CI pipeline.', conflicts: ['cicd-github-actions'] }),
  feature({ id: 'admin-custom', name: 'Custom admin', category: 'admin', description: 'Custom React admin dashboard.' }),
  feature({ id: 'admin-refine', name: 'Refine', category: 'admin', description: 'Refine admin dashboard.' }),
  feature({ id: 'admin-react-admin', name: 'React Admin', category: 'admin', description: 'React Admin dashboard.' }),
  feature({ id: 'tenant-shared-db', name: 'Shared-database tenancy', category: 'tenancy', description: 'Tenant isolation in one database.' }),
  feature({ id: 'tenant-db-per-tenant', name: 'Database-per-tenant', category: 'tenancy', description: 'Dedicated database per tenant.' }),
  feature({ id: 'openapi-openapi', name: 'OpenAPI', category: 'docs', description: 'OpenAPI specification.' }),
  feature({ id: 'openapi-swagger', name: 'Swagger UI', category: 'docs', description: 'Swagger UI at /api/docs.', dependencies: ['openapi-openapi'] }),
  feature({ id: 'openapi-openapi+client', name: 'OpenAPI client', category: 'docs', description: 'OpenAPI plus generated TypeScript client.', dependencies: ['openapi-openapi'] }),
  feature({ id: 'audit-log', name: 'Audit logging', category: 'security', description: 'Actor/action audit trail.' }),
  feature({ id: 'cqrs-basic', name: 'Basic CQRS', category: 'architecture', description: 'Command and query separation.' }),
  feature({ id: 'cqrs-events', name: 'CQRS + Events', category: 'architecture', description: 'CQRS with domain events.', dependencies: ['cqrs-basic'] }),
  feature({ id: 'events-in-process', name: 'In-process events', category: 'architecture', description: 'In-process event bus.' }),
  feature({ id: 'events-redis-pubsub', name: 'Redis Pub/Sub', category: 'architecture', description: 'Redis pub/sub events.', dependencies: ['cache-redis'] }),
  feature({ id: 'events-queue', name: 'Queue events', category: 'architecture', description: 'Queue-backed events.', dependencies: ['queue-bullmq'] }),
  feature({ id: 'arch-modular-monolith', name: 'Modular Monolith', category: 'architecture', description: 'Feature modules.' }),
  feature({ id: 'arch-simple-mvc', name: 'Simple MVC', category: 'architecture', description: 'Simple MVC layout.' }),
  feature({ id: 'arch-layered', name: 'Layered', category: 'architecture', description: 'Layered architecture.' }),
  feature({ id: 'arch-clean', name: 'Clean Architecture', category: 'architecture', description: 'Clean architecture rings.' }),
  feature({ id: 'arch-hexagonal', name: 'Hexagonal', category: 'architecture', description: 'Ports and adapters.' }),
  feature({ id: 'arch-ddd', name: 'DDD', category: 'architecture', description: 'Domain-driven design.' }),
];
