import { execFile } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { confirm } from '@clack/prompts';
import { stringify as stringifyYaml } from 'yaml';
import { readManifest } from '../core/config.js';
import { GenerationEngine } from '../core/engine.js';
import type {
  GenerationPlan,
  Manifest,
  PackageManager,
  PlannedFile,
  StarterConfig,
  ValidationIssue,
} from '../core/types.js';
import { FEATURE_CATALOG } from '../features/catalog.js';
import { applyFeatureToConfig, featuresFromConfig } from '../features/selection.js';
import { formatGeneratedFile } from '../utils/format.js';
import { pathExists, writeFileEnsured } from '../utils/fs.js';
import { CliError, handleCancel, printDryRun } from './print.js';

const execFileAsync = promisify(execFile);

export function getCliVersion(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [join(here, '../../package.json'), join(here, '../../../package.json')];
  for (const candidate of candidates) {
    try {
      const pkg = JSON.parse(readFileSync(candidate, 'utf8')) as { name?: string; version?: string };
      if (pkg.name === 'pern-starter' && pkg.version) return pkg.version;
    } catch {
      // keep looking
    }
  }
  return '1.0.0';
}

export async function loadProject(cwd = process.cwd()): Promise<{ config: StarterConfig; cwd: string }> {
  try {
    const config = await readManifest(cwd);
    if (!config) {
      throw new CliError(
        'No starter.json found',
        'This command must be run inside a project generated by pern-starter.',
        'Run this command from the project root, or create a project with `pern-starter new <name>`.',
      );
    }
    return { config, cwd };
  } catch (error) {
    if (error instanceof CliError) throw error;
    const message = error instanceof Error ? error.message : String(error);
    throw new CliError(
      'Could not read starter.json',
      message,
      'Fix starter.json so it matches the pern-starter schema, then retry.',
    );
  }
}

export async function writeManifest(cwd: string, config: StarterConfig): Promise<void> {
  const manifest: Manifest = {
    version: 1,
    stack: 'PERN',
    generatedAt: new Date().toISOString(),
    generatorVersion: getCliVersion(),
    config,
  };
  await writeFileEnsured(join(cwd, 'starter.json'), `${JSON.stringify(manifest, null, 2)}\n`);
}

export async function writePlannedFiles(
  files: PlannedFile[],
  cwd: string,
  options: { force?: boolean; dryRun?: boolean } = {},
): Promise<{ created: string[]; modified: string[]; skipped: string[] }> {
  const created: string[] = [];
  const modified: string[] = [];
  const skipped: string[] = [];

  for (const file of files) {
    const abs = join(cwd, file.path);
    const exists = pathExists(abs);
    if (options.dryRun) {
      if (exists) modified.push(file.path);
      else created.push(file.path);
      continue;
    }
    if (exists && !options.force) {
      skipped.push(file.path);
      continue;
    }
    const formatted = await formatGeneratedFile(file.path, file.contents);
    await writeFileEnsured(abs, formatted);
    if (exists) modified.push(file.path);
    else created.push(file.path);
  }

  return { created, modified, skipped };
}

const FEATURE_ALIASES: Record<string, string> = {
  redis: 'cache-redis',
  stripe: 'pay-stripe',
  paypal: 'pay-paypal',
  bkash: 'pay-bkash',
  nagad: 'pay-nagad',
  bullmq: 'queue-bullmq',
  prisma: 'orm-prisma',
  drizzle: 'orm-drizzle',
  jwt: 'auth-jwt',
  session: 'auth-session',
  oauth: 'auth-oauth2',
  oauth2: 'auth-oauth2',
  docker: 'docker-dev',
  sentry: 'mon-sentry',
  mailpit: 'mailpit',
  swagger: 'openapi-swagger',
};

export function resolveFeatureId(input: string): string {
  const needle = input.trim().toLowerCase();
  if (!needle) {
    throw new CliError('Feature id is required', undefined, 'Pass a feature id from `pern-starter features`.');
  }
  if (FEATURE_ALIASES[needle]) return FEATURE_ALIASES[needle];

  const exact = FEATURE_CATALOG.find((feature) => feature.id.toLowerCase() === needle);
  if (exact) return exact.id;

  const byName = FEATURE_CATALOG.filter((feature) => feature.name.toLowerCase() === needle);
  if (byName.length === 1) return byName[0]!.id;

  const bySuffix = FEATURE_CATALOG.filter(
    (feature) => feature.id.toLowerCase() === needle || feature.id.toLowerCase().endsWith(`-${needle}`),
  );
  if (bySuffix.length === 1) return bySuffix[0]!.id;
  if (bySuffix.length > 1) {
    throw new CliError(
      `Ambiguous feature "${input}"`,
      `Matches: ${bySuffix.map((feature) => feature.id).join(', ')}`,
      'Use a full feature id from `pern-starter features`.',
    );
  }

  throw new CliError(
    `Unknown feature: ${input}`,
    `"${input}" is not in the feature catalog.`,
    'Run `pern-starter features` to see available ids.',
  );
}

export function autoFixConfig(config: StarterConfig): StarterConfig {
  const next = structuredClone(config);
  if (next.queue === 'bullmq' && next.cache !== 'redis') next.cache = 'redis';
  if (next.backend.api.includes('graphql') && !next.backend.graphqlServer) {
    next.backend.graphqlServer = 'apollo';
  }
  if (next.events === 'redis-pubsub' && next.cache !== 'redis') next.cache = 'redis';
  if (next.events === 'queue' && next.queue !== 'bullmq') next.queue = 'bullmq';
  if (next.events === 'queue' && next.cache !== 'redis') next.cache = 'redis';
  return next;
}

function dependencyIdFromIssue(issue: ValidationIssue): string | undefined {
  const fromMessage = issue.message.match(/Dependency:\s*([A-Za-z0-9._+-]+)/);
  if (fromMessage?.[1]) return fromMessage[1];
  if (issue.path === 'queue' || issue.message.toLowerCase().includes('bullmq requires redis')) {
    return 'cache-redis';
  }
  if (issue.path === 'backend.graphqlServer') return 'graphql-apollo';
  if (issue.fix?.startsWith('Add ')) {
    const match = issue.fix.match(/Add\s+([A-Za-z0-9._+-]+)/);
    if (match?.[1] && match[1] !== 'Redis') return match[1];
  }
  return undefined;
}

export async function resolveMissingDependencies(
  config: StarterConfig,
  options: { yes?: boolean },
): Promise<StarterConfig> {
  const engine = new GenerationEngine();
  let next = structuredClone(config);
  const asked = new Set<string>();

  for (let i = 0; i < 8; i += 1) {
    const missing = [
      ...engine.dependency.requiredPrompts(next),
      ...engine.conflicts.detect(next).filter((issue) => issue.code === 'MISSING_DEPENDENCY'),
    ];
    if (!missing.length) return next;

    for (const issue of missing) {
      const depId = dependencyIdFromIssue(issue);
      const key = depId ?? issue.path ?? issue.message;
      if (asked.has(key)) {
        throw new CliError(issue.message, issue.message, issue.fix);
      }
      asked.add(key);

      const feature = depId ? engine.features.get(depId) : undefined;
      const name = feature?.name ?? depId ?? 'the required dependency';
      let add = Boolean(options.yes);
      if (!options.yes) {
        const answer = await confirm({
          message: `Add ${name} automatically?`,
          initialValue: true,
        });
        add = handleCancel(answer);
      }

      if (!add) {
        throw new CliError(
          issue.message,
          `${name} is required by the current selection and was not added.`,
          issue.fix ?? `Re-run and accept adding ${name}, or disable the dependent feature.`,
        );
      }

      if (depId) next = applyFeatureToConfig(next, depId);
      if (depId === 'cache-redis' || issue.path === 'queue') next.cache = 'redis';
      if (depId === 'graphql-apollo' || issue.path === 'backend.graphqlServer') {
        next.backend.graphqlServer = next.backend.graphqlServer ?? 'apollo';
      }
      if (depId === 'queue-bullmq') next.queue = 'bullmq';
    }
  }

  return next;
}

export async function confirmContinue(message = 'Continue?', yes?: boolean): Promise<boolean> {
  if (yes) return true;
  if (!process.stdin.isTTY) return true;
  const answer = await confirm({ message, initialValue: true });
  return handleCancel(answer);
}

export function planDelta(before: GenerationPlan, after: GenerationPlan): {
  create: PlannedFile[];
  modify: PlannedFile[];
  remove: PlannedFile[];
  packages: GenerationPlan['packages'];
  env: GenerationPlan['env'];
} {
  const beforeMap = new Map(before.files.map((file) => [file.path, file]));
  const afterMap = new Map(after.files.map((file) => [file.path, file]));
  const create: PlannedFile[] = [];
  const modify: PlannedFile[] = [];
  const remove: PlannedFile[] = [];

  for (const file of after.files) {
    const previous = beforeMap.get(file.path);
    if (!previous) create.push({ ...file, action: 'create' });
    else if (previous.contents !== file.contents) modify.push({ ...file, action: 'modify' });
  }
  for (const file of before.files) {
    if (!afterMap.has(file.path)) remove.push(file);
  }

  const beforePkgs = new Set(before.packages.map((pkg) => `${pkg.workspace}:${pkg.name}`));
  const packages = after.packages.filter((pkg) => !beforePkgs.has(`${pkg.workspace}:${pkg.name}`));
  const beforeEnv = new Set(before.env.map((item) => item.key));
  const env = after.env.filter((item) => !beforeEnv.has(item.key));

  return { create, modify, remove, packages, env };
}

export function printInstallPlan(delta: ReturnType<typeof planDelta>, cwd: string): void {
  const files: PlannedFile[] = [
    ...delta.create,
    ...delta.modify.map((file) => ({ ...file, action: 'modify' as const })),
  ];
  printDryRun(
    {
      projectName: '',
      destination: cwd,
      files,
      packages: delta.packages,
      env: delta.env,
      dockerServices: [],
      scripts: {},
      features: [],
      warnings: [],
      notes: [],
    },
    cwd,
  );
  if (delta.remove.length) {
    console.log('Files that would be removed:');
    for (const file of delta.remove) {
      console.log(`- ${file.path}`);
    }
    console.log();
  }
}

export async function runInstall(
  pm: PackageManager,
  cwd: string,
): Promise<void> {
  const bin = pm === 'npm' ? 'npm' : pm;
  const args = pm === 'yarn' ? ['install'] : ['install'];
  try {
    await execFileAsync(bin, args, {
      cwd,
      timeout: 10 * 60 * 1000,
      windowsHide: true,
      shell: process.platform === 'win32',
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new CliError(
      `${pm} install failed`,
      message,
      `Run \`${pm} install\` in ${cwd} after fixing the error.`,
    );
  }
}

export function selectedFeatureNames(config: StarterConfig): string[] {
  const ids = featuresFromConfig(config);
  return ids.map((id) => FEATURE_CATALOG.find((feature) => feature.id === id)?.name ?? id);
}

export function dumpConfig(config: StarterConfig, format: 'json' | 'yaml' = 'yaml'): string {
  if (format === 'json') return `${JSON.stringify(config, null, 2)}\n`;
  return stringifyYaml(config);
}

export async function safeExec(
  command: string,
  args: string[],
  options: { timeout?: number } = {},
): Promise<{ ok: boolean; output: string }> {
  try {
    const { stdout, stderr } = await execFileAsync(command, args, {
      timeout: options.timeout ?? 8000,
      windowsHide: true,
      shell: process.platform === 'win32',
    });
    return { ok: true, output: `${stdout}${stderr}`.trim() };
  } catch {
    return { ok: false, output: '' };
  }
}

export function isInteractive(yes?: boolean): boolean {
  return Boolean(process.stdin.isTTY) && !yes;
}
