import type { ArchitectureDefinition } from '../core/types.js';

export const ARCHITECTURE_CATALOG: ArchitectureDefinition[] = [
  {
    id: 'simple-mvc',
    name: 'Simple MVC',
    description: 'Controllers, services, and routes with minimal layering.',
    compatibleWith: ['repository', 'service-layer', 'monorepo'],
    conflicts: ['ddd', 'cqrs', 'hexagonal'],
  },
  {
    id: 'layered',
    name: 'Layered Architecture',
    description: 'Presentation, business, and data layers with clear direction.',
    compatibleWith: ['repository', 'service-layer', 'monorepo'],
    conflicts: [],
  },
  {
    id: 'service-layer',
    name: 'Service Layer',
    description: 'Business logic lives in services; controllers stay thin.',
    compatibleWith: ['simple-mvc', 'layered', 'repository', 'modular-monolith', 'monorepo'],
    conflicts: [],
  },
  {
    id: 'repository',
    name: 'Repository Pattern',
    description: 'Persistence is isolated behind repository interfaces.',
    compatibleWith: ['simple-mvc', 'layered', 'service-layer', 'modular-monolith', 'clean', 'ddd'],
    conflicts: [],
  },
  {
    id: 'modular-monolith',
    name: 'Modular Monolith',
    description: 'Feature modules own routes, services, repositories, and tests.',
    compatibleWith: ['repository', 'service-layer', 'monorepo', 'multi-tenant'],
    conflicts: [],
  },
  {
    id: 'clean',
    name: 'Clean Architecture',
    description: 'Domain at the center with application, infrastructure, and presentation rings.',
    compatibleWith: ['hexagonal', 'ddd', 'repository', 'monorepo'],
    conflicts: ['simple-mvc'],
  },
  {
    id: 'hexagonal',
    name: 'Hexagonal Architecture',
    description: 'Ports and adapters isolate the application from infrastructure.',
    compatibleWith: ['clean', 'ddd', 'monorepo'],
    conflicts: ['simple-mvc'],
  },
  {
    id: 'ddd',
    name: 'Domain-Driven Design',
    description: 'Aggregates, value objects, domain events, and bounded contexts.',
    compatibleWith: ['clean', 'hexagonal', 'cqrs', 'event-driven', 'monorepo'],
    conflicts: ['simple-mvc'],
  },
  {
    id: 'cqrs',
    name: 'CQRS',
    description: 'Separate command and query models. Never enabled automatically for simple CRUD.',
    compatibleWith: ['ddd', 'event-driven', 'modular-monolith'],
    conflicts: ['simple-mvc'],
  },
  {
    id: 'event-driven',
    name: 'Event Driven',
    description: 'In-process or brokered events between modules.',
    compatibleWith: ['ddd', 'cqrs', 'modular-monolith', 'microservice-ready'],
    conflicts: [],
  },
  {
    id: 'microservice-ready',
    name: 'Microservice Ready',
    description: 'Shared contracts and service boundaries without splitting until requested.',
    compatibleWith: ['modular-monolith', 'event-driven', 'monorepo'],
    conflicts: [],
  },
  {
    id: 'monorepo',
    name: 'Monorepo',
    description: 'apps/api, apps/web, and optional shared packages.',
    compatibleWith: [
      'simple-mvc',
      'layered',
      'modular-monolith',
      'clean',
      'ddd',
      'hexagonal',
    ],
    conflicts: [],
  },
  {
    id: 'multi-tenant',
    name: 'Multi-Tenant',
    description: 'Tenant isolation via shared database or database-per-tenant.',
    compatibleWith: ['modular-monolith', 'ddd', 'clean'],
    conflicts: [],
  },
];
