import type { PatternDefinition } from '../core/types.js';

export const PATTERN_CATALOG: PatternDefinition[] = [
  { id: 'factory', name: 'Factory', category: 'creational', description: 'Create objects without exposing construction logic.' },
  { id: 'abstract-factory', name: 'Abstract Factory', category: 'creational', description: 'Create families of related objects.' },
  { id: 'builder', name: 'Builder', category: 'creational', description: 'Construct complex objects step by step.' },
  { id: 'prototype', name: 'Prototype', category: 'creational', description: 'Clone existing instances.' },
  {
    id: 'singleton',
    name: 'Singleton',
    category: 'creational',
    description: 'One shared instance.',
    warn: 'Avoid unnecessary Singleton usage. Prefer module scope and dependency injection.',
  },
  { id: 'adapter', name: 'Adapter', category: 'structural', description: 'Make incompatible interfaces work together.' },
  { id: 'bridge', name: 'Bridge', category: 'structural', description: 'Decouple abstraction from implementation.' },
  { id: 'composite', name: 'Composite', category: 'structural', description: 'Treat tree structures uniformly.' },
  { id: 'decorator', name: 'Decorator', category: 'structural', description: 'Add behavior without subclassing.' },
  { id: 'facade', name: 'Facade', category: 'structural', description: 'Provide a simplified interface to a subsystem.' },
  { id: 'proxy', name: 'Proxy', category: 'structural', description: 'Control access to another object.' },
  { id: 'strategy', name: 'Strategy', category: 'behavioral', description: 'Swap algorithms behind a common contract.' },
  { id: 'command', name: 'Command', category: 'behavioral', description: 'Encapsulate a request as an object.' },
  { id: 'observer', name: 'Observer', category: 'behavioral', description: 'Notify subscribers of state changes.' },
  { id: 'state', name: 'State', category: 'behavioral', description: 'Alter behavior when internal state changes.' },
  { id: 'chain-of-responsibility', name: 'Chain of Responsibility', category: 'behavioral', description: 'Pass requests along a handler chain.' },
  { id: 'mediator', name: 'Mediator', category: 'behavioral', description: 'Centralize communication between objects.' },
  { id: 'template-method', name: 'Template Method', category: 'behavioral', description: 'Define an algorithm skeleton with overridable steps.' },
  { id: 'specification', name: 'Specification', category: 'behavioral', description: 'Encapsulate business rules as composable predicates.' },
  { id: 'service-layer', name: 'Service Layer', category: 'application', description: 'Application services coordinate use-cases.' },
  { id: 'repository', name: 'Repository', category: 'application', description: 'Collection-like access to aggregates.' },
  { id: 'use-case', name: 'Use Case', category: 'application', description: 'One application operation per class or function.' },
  { id: 'dto', name: 'DTO', category: 'application', description: 'Transfer data across boundaries.' },
  { id: 'mapper', name: 'Mapper', category: 'application', description: 'Map between domain and persistence/API models.' },
  { id: 'unit-of-work', name: 'Unit of Work', category: 'application', description: 'Track changes and commit atomically.' },
  { id: 'domain-event', name: 'Domain Event', category: 'application', description: 'Record something that happened in the domain.' },
  { id: 'event-bus', name: 'Event Bus', category: 'application', description: 'Publish and subscribe to events.' },
  { id: 'saga', name: 'Saga', category: 'application', description: 'Coordinate long-running business transactions.' },
];
